# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev

variables:
- name: REPOSITORY_NAME
  value: 'repository_name_value'
- name: TARGET
  value: 'target_value' 
- name: AWS_CREDENTIALS
  value: 'aws_credentials_value'
- name: AWS_REGION
  value: 'us-east-1'
- name: IMAGE_NAME
  value: 'image_name'
   
resources:
- repo: self


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: '$(REPOSITORY_NAME)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
        arguments: '--target $(TARGET) --cache-from=$(TARGET) --build-arg ENV=$(Build.SourceBranchName)'
        addPipelineData: false
        addBaseImageData: false   


    - task: ECRPushImage@1
      displayName: Push image to ECR (revision-commit-tag)
      inputs:
        awsCredentials: '$(AWS_CREDENTIALS)'
        regionName: '$(AWS_REGION)'
        imageSource: '$(IMAGE_NAME)'
        sourceImageName: '$(REPOSITORY_NAME)'
        sourceImageTag: '$(Build.BuildId)'
        repositoryName: '$(REPOSITORY_NAME)'
        pushTag: 'latest'
        autoCreateRepository: true
